apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: synapse
      app: synapse
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: synapse
        app: synapse
    spec:
      containers:
        - name: ufi
          image: grantdhunter/update_floating_ip:v2
          imagePullPolicy: IfNotPresent
          env:
            - name: DO_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: do-access
                key: DIGITALOCEAN_ACCESS_TOKEN
          args: ["--wait", "goatchat.ca"]
          restartPolicy: OnFailure
